### ISSUE TITLE
Sometimes there are no words left to choose from

### ISSUE THREAD

**Issue by Jack-Dane** [Jack-Dane/wordle-solver#2]
```Traceback (most recent call last):
  File "/home/jack/Documents/Python/wordle/venv/bin/wordleRun", line 33, in <module>
    sys.exit(load_entry_point('wordle', 'console_scripts', 'wordleRun')())
  File "/home/jack/Documents/Python/wordle/wordle/main.py", line 41, in main
    wordle.start(cheat=options.cheat, vnc=options.VNC)
  File "/home/jack/Documents/Python/wordle/wordle/wordProcessing/wordle.py", line 33, in start
    self._run()
  File "/home/jack/Documents/Python/wordle/wordle/wordProcessing/wordle.py", line 55, in _run
    self.nextGuess = wordProcessor.getNextGuess()
  File "/home/jack/Documents/Python/wordle/wordle/wordProcessing/wordProcessor.py", line 77, in getNextGuess
    return self._wordList.nextWord()
  File "/home/jack/Documents/Python/wordle/wordle/wordProcessing/wordList.py", line 40, in nextWord
    return random.sample(self.wordList, 1)[0]
  File "/usr/lib/python3.8/random.py", line 363, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative```

**Comment by Jack-Dane** [comment]
Example of failure: 
```
class
wagyu
zoppa
```
for the correct word: adopt
